### ISSUE TITLE
TransportError: TransportError(406, 'Content-Type header [] is not supported')

### ISSUE THREAD

**Issue by mar10nJohns1** [Niels-Peter/XBRL-AI#12]
There seems to be an error when using the scanscroll_fetchlist_dk function. 

I've looked around but can't seem to find a solution. 

Apart from the error-message stated in the header, I receive this message right under the line of code that uses the scanscroll function:
GET /offentliggoerelser/_search?scroll=5m&search_type=scan&size=128 [status:406 request:0.107s]

Any idea about what might solve this issue? Thanks!

**Comment by soetang** [comment]
The Danish Business Authority have just changed their elasticsearch API. However they still maintain a legacy API. The newest version uses the legacy API as tempoary solution, maybe this solves your problem?

**Comment by mar10nJohns1** [comment]
Thanks for the help @soetang , but even with the new version using the legacy API it gives the same error..

**Comment by soetang** [comment]
I am able to replicate it now. 

When i run it using IPython in the Spyder IDE it works. However when using ipython from the console i get the error message. Both should use the same conda enviroment on my machine, so i am a bit unsure on what the exact problem is.

**Comment by mar10nJohns1** [comment]
Great thank you. The solution is as you said, reinstalling the framework. 

I reinstalled Anaconda, downloaded a new zip of this framework, and followed the installation procedure of the XBRL-AI cf. the README.md.
